---
theme: jekyll-theme-minimal
title: "Bill Wallis: Data Ninja 🥷"
logo: https://avatars.githubusercontent.com/u/25640332?v=4
description: >
  Mathematician masquerading as a programmer.
  
  [View My LinkedIn Profile](https://www.linkedin.com/in/bill-wallis/)
  
  [View My Stack Overflow Profile](https://stackoverflow.com/users/8213085/bill-wallis?tab=profile)
