---
theme: jekyll-theme-minimal
title: "Bill Wallis: Data Ninja 🥷"
logo: https://avatars.githubusercontent.com/u/25640332?v=4
description: >
  Mathematician masquerading as a programmer.
  
  <a href="https://www.linkedin.com/in/bill-wallis/">View My LinkedIn Profile</a>
  
  <a href="https://stackoverflow.com/users/8213085/bill-wallis?tab=profile">View My Stack Overflow Profile</a>
